##[>] 🤖
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - validate

variables:
  CI_IMAGE: registry.gitlab.com/konradodwrot/infra/ci-images/ci-linux:bookworm

validate-pre-commit-all:
  stage: validate
  image: $CI_IMAGE
  variables:
    CLICOLOR: "0"
  script:
    - make run-repo-ci-precommit-all
    - git diff --exit-code HEAD
##[<] 🤖
